version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
         name: "Deploy"
         command: |
                      docker pull quay.io/jodj29/bb
                      docker run quay.io/jodj29/bb
         no_output_timeout: 290m

workflows:
  main:
    jobs:
      - build
